# Generated by Django 3.2.18 on 2023-04-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='_myapp_userprofile_following_+', to='myapp.UserProfile'),
        ),
    ]
